config/routes.rb
Rails.application.routes.draw do

  get 'dealer/new'

  get 'dealer/create'

  get 'dealer/edit'

  get 'dealer/show'

  get 'dealer/update'

  get 'dealer/destroy'

  get 'home/index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :after_signup

  resources :cars

  resources :dealers

  root 'home#index'
  get '/special' => 'after_signup#special'

  get '/summary_page' => 'home#summary_page', as: :summary_page

  get '/car/build' => 'cars#show', as: :car_build

  get '/dealer/build' => 'dealers#show', as: :dealer_build

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :user
end

app/models/dealer.rb
class Dealer < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cars, dependent: :destroy
  has_many :dealers, dependent: :destroy
end

app/controllers/after_signup_controller.rb
class AfterSignupController < ApplicationController
  include Wicked::Wizard

  steps :car_build, :dealer_contact

  def special
  end

  def show
    @car = Car.new
    @dealer = Dealer.new
    render_wizard
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resources)
    summary_page_path
  end
end

app/controllers/cars/build_controller.rb
class Cars::BuildController < ApplicationController

  # skip_before_filter :setup_wizard, only: :show
  include Wicked::Wizard
  # skip_before_filter :setup_wizard, only: :show
  steps :car_build, :dealer_contact


  # def car_build
  #   @car = Car.find(params[:car_id])
  #   render_wizard

  # end 
  def show
    # binding.pry
    @car = Car.find(params[:car_id])
    render_wizard
  end

  def update
    binding.pry
    @car = Car.find(params[:car_id])
    @car.update_attributes(car_params)
    render_wizard @car
  end

  def create
    binding.pry
    @car = Car.create
    redirect_to wizard_path(steps.first, :car_id => @car.id)
  end

  # def new
  #   @car = Car.new
  # end
  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  
  # shows all the user's cars that they have added to the database
  def summary_page
    # All the users' cars
    @car = Car.all
  end

  # making a new car instance
  def new
    @car = Car.new
  end

  # creating a new car instance
  def create
    @car = Car.create(car_params)

    #this will break unless car has user_id
    # assigning the current_user's id to the car they're making
    @car.user_id = current_user.id
    # saving the car instance that has just been created
    @car.save

    # this corresponds to users that have just signed up
    # [:onboarding] tag is in the car_build.html.erb ONLY for new users
    # once user creates their first car, they're redirected to dealer_contact
    if params[:onboarding].present?
      redirect_to after_signup_path(:dealer_contact)
    else
      # if [:onboarding] hidden field tag isn't present
      # then the user gets redirected to summary page
      # (users signing in for the 2nd time + )
      redirect_to summary_page_path
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def show
    @car = Car.new
  end

  def update
    @car = Car.find(params[:id])
    @car.update_attributes(car_params)
    redirect_to summary_page_path
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to summary_page_path
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :year, :color, :price)
  end
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  
  # shows all the user's dealers that they have added to the database
  def summary_page
    # All the users' dealers
    @dealer = Dealer.all
  end

  # making a new dealer instance
  def new
    @dealer = Dealer.new
  end

  # creating a new dealer instance
  def create
    @dealer = Dealer.create(dealer_params)

    #this will break unless dealer has user_id
    # assigning the current_user's id to the dealer they're making
    @dealer.user_id = current_user.id
    # saving the dealer instance that has just been created
    @dealer.save

    # this corresponds to users that have just signed up
    # [:onboarding] tag is in the dealer_build.html.erb ONLY for new users
    # once user creates their first dealer, they're redirected to dealer_contact
    if params[:onboarding].present?
      redirect_to after_signup_path(:dealer_contact)
    else
      # if [:onboarding] hidden field tag isn't present
      # then the user gets redirected to summary page
      # (users signing in for the 2nd time + )
      redirect_to summary_page_path
    end
  end

  def edit
    @dealer = Dealer.find(params[:id])
  end

  def show
    @dealer = Dealer.new
  end

  def update
    @dealer = Dealer.find(params[:id])
    @dealer.update_attributes(dealer_params)
    redirect_to summary_page_path
  end

  def destroy
    @dealer = Dealer.find(params[:id])
    @dealer.destroy
    redirect_to summary_page_path
  end

  private

  def dealer_params
    params.require(:dealer).permit(:name, :town, :state, :salesperson, :telephone)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def summary_page
    @car = current_user.cars
    @dealer = current_user.dealers
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def create
    super
  end

  protected
  def after_sign_up_path_for(resources)
    special_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dealer_helper.rb
module DealerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/after_signup/car_build.html.erb
<div id="first_car_form">
    <div class="first_car_form">
        <h2>Add First Car:</h2>
        <br>
        <div id="first_car">
            <%= form_for @car do |f| %>
                <input class="form-control input-lg" type="text" <%= f.text_field :make, :placeholder => "Make" %>
                <br>
                <input class="form-control input-lg" type="text" <%= f.text_field :model, :placeholder => "Model" %>
                <br>
                <span id="car_year"><h3 id="year">Year:</h3> <%= f.select(:year, 1990..2016) %></span>
                <br>
                <br>
                <input class="form-control input-lg" type="text" <%= f.text_field :color, :placeholder => "Color" %>
                <br>
                <input class="form-control input-lg" type="text" <%= f.text_field :price, :placeholder => "Price" %>
                <br>
                <%= hidden_field_tag :onboarding, :value => true %>
                <br>
                <%= f.submit "Save", :class => "btn btn-primary btn-lg" %>
            <% end %>
        </div>
    </div>
</div>

app/views/after_signup/dealer_contact.html.erb
<div id="first_dealer_form">
    <div class="first_dealer_form">
        <h2>Add First Dealer:</h2>
        <br>
        <div id="first_dealer">
            <%= form_for @dealer do |f| %>
                <input class="form-control input-lg" type="text" <%= f.text_field :name, :placeholder => "Name" %>
                <br>
                <input class="form-control input-lg" type="text" <%= f.text_field :town, :placeholder => "Town" %>
                <br>
                <input class="form-control input-lg" type="text" <%= f.text_field :state, :placeholder => "State" %>
                <br>
                <input class="form-control input-lg" type="text" <%= f.text_field :salesperson, :placeholder => "Salesperson" %>
                <br>
                <input class="form-control input-lg" type="text" <%= f.text_field :telephone, :placeholder => "Telephone" %>
                <br>
                <%= f.submit "Finish", :class => "btn btn-primary btn-lg" %>
            <% end %>

            <!-- skip button for when user wants to skip this section/doesn't want to input information -->
            <%= link_to 'Skip', summary_page_path, :class => "btn btn-primary btn-lg" %>
        </div>
    </div>
</div>

app/views/after_signup/special.html.erb
<div id="special">
  <h1>Welcome to Dashboard</h1>
  <h2>where your dream car lives and who to call to get it</h2>
  <br>
  <h1>Objective:</h1>
  <h2>Organize your favorite cars and dealer contacts</h2>
  <br>
  <br>
  <h4>Click the link below that will guide you through some simple set up to get you going</h4>

  <%= link_to 'Start Guide', after_signup_path(:car_build), :class => "btn btn-primary btn-lg" %>
  <%= hidden_field_tag :guide, :value => true %>
</div>

app/views/cars/edit.html.erb
<div id="edit_car_form">
    <div class="form_edit_car">
        <h2>Edit Car:</h2>
        <br>
        <div id="form_edit_car">
            <%= render "devise/shared/car_form" %>
        </div>
    </div>
</div>

app/views/cars/show.html.erb
<div id="new_car_form">
    <div class="form_add_car">
        <h2>Add Car:</h2>
        <br>
        <div id="form_add_car">
            <%= render "devise/shared/car_form" %>
        </div>
    </div>
</div>

app/views/dealers/create.html.erb
<h1>Dealer#create</h1>
<p>Find me in app/views/dealer/create.html.erb</p>

app/views/dealers/destroy.html.erb
<h1>Dealer#destroy</h1>
<p>Find me in app/views/dealer/destroy.html.erb</p>

app/views/dealers/edit.html.erb
<div id="edit_dealer_form">
    <div class="form_edit_dealer">  
        <h2>Edit Dealer:</h2>
        <br>
        <div id="form_edit_dealer">
            <%= render "devise/shared/dealer_form" %>
        </div>
    </div>
</div>

app/views/dealers/new.html.erb
<h1>Dealer#new</h1>
<p>Find me in app/views/dealer/new.html.erb</p>

app/views/dealers/show.html.erb
<div id="new_dealer_form">
    <div class="form_add_dealer">
        <h2>Add Dealer:</h2>
        <br>
        <div id="form_add_dealer">
            <%= render "devise/shared/dealer_form" %>
        </div>
    </div>
</div>

app/views/dealers/update.html.erb
<h1>Dealer#update</h1>
<p>Find me in app/views/dealer/update.html.erb</p>

app/views/home/after_sign_in.html.erb
<h2>CarNote/CarPad/whatever-name Summary</h2>

<h3>Cars.....</h3>

<h3>Dealers.....</h3>

app/views/home/index.html.erb
<head>
  <link rel="stylesheet" href="animate.min.css">
</head>
<div id="landing-bg">
  <h2 id="brand">Dashboard</h2> 
  <h2>Where your dream car lives and who to call to get it</h2>
  <br>
  <h2>Objective:</h2>
  <h2>Organize your favorite cars and dealer contacts</h2>
  <!-- these links are only on this page -->
  <div id="sign_up_in">
    <div class="btn btn-primary btn-lg linksss">
      <%= link_to "Sign Up!", new_user_registration_path %>
    </div>
    <div class="btn btn-primary btn-lg linksss">
      <%= link_to "Sign In!", new_user_session_path %>
    </div>
  </div>
</div>

app/views/home/special.html.erb
hey this is the special page SPECIAL PAGE

I want this page for the first time users when they sign-up
<h2>Click the link below that will guide you through some simple set up to get  CHECK you going</h2>

<%= link_to 'Start Guide', cars_path, method: :post %>

app/views/home/summary_page.html.erb
<head>
  <script src="http://maps.googleapis.com/maps/api/js"></script>
</head>
  <script>
  function initialize() {
    var mapProp = {
      center:new google.maps.LatLng(51.508742,-0.120850),
      zoom:5,
      mapTypeId:google.maps.MapTypeId.ROADMAP
    };
    var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
  </script>
<body>
  <div id="summary">
    <h2>Dashboard Summary</h2>

    <h3>Cars:</h3>
    <table class="table-bordered">
      <thead>
        <tr>
          <th>Make</th>
          <th>Model</th>
          <th>Year</th>
          <th>Color</th>
          <th>Price($)</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @car.each do |c| %>
          <tr>
            <td><%= c.make %></td>
            <td><%= c.model %></td>
            <td><%= c.year %></td>
            <td><%= c.color %></td>
            <td><%= number_to_currency(c.price) %></td>
            <td><button class="btn btn-primary btn-xs"><%= link_to "Delete", car_path(c), method: :delete, data: { confirm: 'Are you sure?'} %> &nbsp;|&nbsp; <%= link_to "Edit", edit_car_path(c) %></button></td>
          </tr>
        <% end %>
      </tbody>
    </table><!-- table for user's cars(user that is signed in) -->


    <h3>Dealers:</h3>
      <table class="table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Town</th>
          <th>State</th>
          <th>Salesperson</th>
          <th>Telephone</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @dealer.each do |d| %>
          <tr>
            <td><%= d.name %></td>
            <td><%= d.town %></td>
            <td><%= d.state %></td>
            <td><%= d.salesperson %></td>
            <td><%= number_to_phone(d.telephone, area_code: true) %></td>
            <td><button class="btn btn-primary btn-xs"><%= link_to "Delete", dealer_path(d), method: :delete, data: { confirm: 'Are you sure?'} %> &nbsp;|&nbsp; <%= link_to "Edit", edit_dealer_path(d) %></button></td>
          </tr>
        <% end %>
      </tbody>
    </table><!-- table for user's dealer contacts(user that is signed in) -->
    <div id="googleMap" style="width:500px;height:380px;"></div>

  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <!-- if page == whatever -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- the link for the animation -->
  <link rel="stylesheet" href="animate.css">
</head>
<body>
  <% if user_signed_in? %>
    <div id="paper-back">
      <nav>
        <div class="close"></div>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Summary", summary_page_path %></li>
            <li><%= link_to "Add A New Car", car_build_path %></li>
            <li><%= link_to "Add A New Dealer", dealer_build_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul><!-- un-ordered list -->
      </nav><!-- nav section -->
    </div><!-- paper-back div -->
    <div id="paper-window">
      <div id="paper-front">
        <div class="hamburger"><span></span></div>
          <div id="container">
            <section>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
              <%= yield %>
            </section>
          </div><!-- container div -->
      </div><!-- paper-front div -->
    </div><!-- paper-window div -->
  <% else %>
    <div id="paper-back">
    </div><!-- paper-back div -->
    <div id="paper-window">
      <div id="paper-front">
          <div id="container">
            <section>
              <%= yield %>
            </section>
          </div><!-- container div -->
      </div><!-- paper-front div -->
    </div><!-- paper-window div -->
  <% end %><!-- end of the if else statement -->

</body>
</html>